version: '3.1'

services:

  mysql:
    image: mysql
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      # Use root/example as user/password credentials
      MYSQL_ROOT_PASSWORD: example

  web-api:
    build: ./services/web-api/
    restart: on-failure
    ports:
      - 5000:5000
    depends_on:
      - mysql
    links:
      - mysql:mysql
